{
    "author": "春风",
    "ua": "",
    "homeUrl": "https://www.llyady.com/",
    "dcVipFlag": "true",
    "pCfgJs": "https://www.llyady.com/static/js/playerconfig.js",
    "pCfgJsR": "MacPlayerConfig.player_list=([\\w\\W]*?),MacPlayerConfig.downer_list=",
    "dcShow2Vip": {},
    "dcPlayUrl": "true",
    "cateManual": {
        "国产剧": "28",
        "日剧韩": "29",
        "欧美剧": "30",
        "港台剧": "31",
        "其它剧": "32",
        "电影": "1",
        "动漫": "3",
        "综艺": "4"
    },
    "homeVodNode": "//div[@class='module-item']",
    "homeVodName": "//div[@class='module-item-pic']/a/@title",
    "homeVodId": "//div[@class='module-item-pic']/a/@href",
    "homeVodIdR": "/video/(\\w+).html",
    "homeVodImg": "//div[@class='module-item-pic']/img/@data-src",
    "homeVodImgR": "",
    "homeVodMark": "//div[@class='module-item-text']/text()",
    "cateUrl": "https://www.llyady.com/vodshow/{cateId}--------{catePg}---.html",
    "cateVodNode": "//div[@class='module-item']",
    "cateVodName": "//div[@class='module-item-pic']/a/@title",
    "cateVodId": "//div[@class='module-item-pic']/a/@href",
    "cateVodIdR": "/video/(\\w+).html",
    "cateVodImg": "//div[@class='module-item-pic']/img/@data-src",
    "cateVodImgR": "",
    "cateVodMark": "//div[@class='module-item-text']/text()",
    "dtUrl": "https://www.llyady.com/video/{vid}.html",
    "dtNode": "//body",
    "dtName": "//h1[@class='page-title']/text()",
    "dtNameR": "",
    "dtImg": "//div[@class='video-cover']//img/@data-src",
    "dtImgR": "",
    "dtCate": "//span[contains(text(), '/')]/following-sibling::a[2]/text()",
    "dtCateR": "",
    "dtYear": "//a[2][@class='tag-link']/text()",
    "dtYearR": "",
    "dtArea": "//a[3][@class='tag-link']/text()",
    "dtAreaR": "",
    "dtDirector": "//span[contains(text(), '导演')]/following-sibling::div/a/text()",
    "dtDirectorR": "",
    "dtActor": "//span[contains(text(), '主演')]/following-sibling::div/a/text()",
    "dtActorR": "",
    "dtDesc": "//span[contains(text(), '剧情')]/following-sibling::div/span/text()",
    "dtDescR": "",
    "dtFromNode": "//div[@class='module-tab-item tab-item']/span",
    "dtFromName": "/text()",
    "dtFromNameR": "",
    "dtUrlNode": "//div[@class='sort-item']",
    "dtUrlSubNode": "/a",
    "dtUrlId": "@href",
    "dtUrlIdR": "/player/(\\S+).html",
    "dtUrlName": "/span/text()",
    "dtUrlNameR": "",
    "playUrl": "https://www.llyady.com/player/{playUrl}.html",
    "playUa": "Mozilla/5.0 (Linux; Android 10; LYA-AL00; HMSCore 6.5.0.312; GMSCore 20.15.16) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 HuaweiBrowser/11.0.4.300 Mobile Safari/537.36",
    "searchUrl": "https://www.llyady.com/vodsearch/-------------.html?wd={wd}",
    "scVodNode": "//div[@class='module-search-item']",
    "scVodName": "//div[@class='video-info-header']/a/@title",
    "scVodId": "//div[@class='video-info-header']/a/@href",
    "scVodIdR": "/video/(\\w+).html",
    "scVodImg": "//img/@data-src",
    "scVodMark": "//div[@class='video-info-header']/a/text()"
}
