{
    "author": "春风",
    "ua": "Mozilla/5.0 (Linux; U; Android 5.0; zh-Hans-CN; HTC 802t Build/KTU84L) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 Quark/5.7.6.217 Mobile Safari/537.36,
    "homeUrl": "https://www.2345ka.com",
    "dcVipFlag": "true",
    "dcPlayUrl": "true",
    "cateManual": {
        "电影": "1",
        "连续剧": "2",
        "动漫": "4",
        "综艺": "3",
        "音乐": "6",
        "福利": "5"
    },
    "homeVodNode": "//div[contains(@class,'list-item')]",
    "homeVodName": "//div[contains(@class,'movie-title')]/text()",
    "homeVodId": "/a/@href",
    "homeVodIdR": "/v/(\\w+).html",
    "homeVodImg": "/a//@data-original",
    "homeVodImgR": "",
    "homeVodMark": "//div[@class='movie-rating cor4']/text()",
    "cateUrl": "https://www.2345ka.com/t/{cateId}/{catePg}.html",
    "cateVodNode": "//div[contains(@class,'list-item')]",
    "cateVodName": "//div[contains(@class,'movie-title')]/text()",
    "cateVodId": "/a/@href",
    "cateVodIdR": "/v/(\\w+).html",
    "cateVodImg": "/a//@data-original",
    "cateVodImgR": "",
    "cateVodMark": "//div[@class='movie-rating cor4']/text()",
    "dtUrl": "https://www.2345ka.com/v/{vid}.html",
    "dtNode": "//div[@class='details']",
    "dtName": "//h1[@class='movie-title']/text()",
    "dtNameR": "",
    "dtImg": "//div[@class='poster']/img/@src",
    "dtImgR": "",
    "dtCate": "//div[@class='scroll-content']/a/text()",
    "dtCateR": "",
    "dtYear": "//div[@class='scroll-content']/a[3]/text()",
    "dtYearR": "",
    "dtArea": "",
    "dtAreaR": "",
    "dtDirector": "",
    "dtDirectorR": "",
    "dtActor": "//p[contains(text(), '演员')]/child::a/text()",
    "dtActorR": "",
    "dtDesc": "//div[@class='summary detailsTxt']/text()",
    "dtDescR": "",
    "dtFromNode": "//div[@class='swiper-wrapper']/a",
    "dtFromName": "/text()",
    "dtFromNameR": "",
    "dtUrlNode": "//ul[contains(@class,'content_playlist')]",
    "dtUrlSubNode": "/li/a",
    "dtUrlId": "@href",
    "dtUrlIdR": "/p/(\\S+).html",
    "dtUrlName": "/text()",
    "dtUrlNameR": "",
    "playUrl": "https://www.2345ka.com/p/{playUrl}.html",
    "playUa": "",
    "searchUrl": "https://www.2345ka.com/search?wd={wd}",
    "scVodNode": "//div[@class='box flex']",
    "scVodName": "//div[contains(@class,'movie-title')]/text()",
    "scVodId": "/a/@href",
    "scVodIdR": "/v/(\\w+).html",
    "scVodImg": "/a/div/@data-original",
    "scVodMark": "//div[@class='movie-rating cor4']/text()"
}
