{
    "author": "春风",
    "ua": "",
    "homeUrl": "https://www.ml1080.com/",
    "dcVipFlag": "true",
    "pCfgJs": "https://www.ml1080.com/static/js/playerconfig.js",
    "pCfgJsR": "MacPlayerConfig.player_list=([\\w\\W]*?),MacPlayerConfig.downer_list=",
    "dcShow2Vip": {},
    "dcPlayUrl": "true",
    "cateManual": {
        "电影": "1",
        "连续剧": "2",
        "动漫": "3",
        "国产剧": "13",
        "港台剧": "14",
        "日韩剧": "15",
        "欧美剧": "16",
        "动作片": "20",
        "喜剧片": "21",
        "爱情片": "22",
        "科幻片": "23",
        "恐怖片": "24",
        "战争片": "25",
        "惊悚片": "26",
        "剧情片": "27",
        "犯罪片": "28",
        "冒险片": "29",
        "悬疑片": "30",
        "武侠片": "31",
        "奇幻片": "32"     
    },
    "homeVodNode": "//a[contains(@class,'myui-vodlist__thumb')]",
    "homeVodName": "/@title",
    "homeVodId": "/@href",
    "homeVodIdR": "/move/(\\w+).html",
    "homeVodImg": "/@data-original",
    "homeVodImgR": "",
    "homeVodMark": "/span[@class='pic-text text-right']/text()",
    "cateUrl": "https://www.ml1080.com/flar/{cateId}-{catePg}.html",
    "cateVodNode": "//a[@class='myui-vodlist__thumb lazyload']",
    "cateVodName": "/@title",
    "cateVodId": "/@href",
    "cateVodIdR": "/move/(\\w+).html",
    "cateVodImg": "/@data-original",
    "cateVodImgR": "",
    "cateVodMark": "/span[@class='pic-text text-right']/text()",
    "dtUrl": "https://www.ml1080.com/move/{vid}.html",
    "dtNode": "//body",
    "dtName": "//div[@class='myui-content__thumb']/a/@title",
    "dtNameR": "",
    "dtImg": "//div[@class='myui-content__thumb']/a/img/@data-original",
    "dtImgR": "",
    "dtCate": "//span[contains(text(), '分类')]/following-sibling::a/text()",
    "dtCateR": "",
    "dtYear": "//span[contains(text(), '年份')]/following-sibling::a/text()",
    "dtYearR": "",
    "dtArea": "//span[contains(text(), '地区')]/following-sibling::a/text()",
    "dtAreaR": "",
    "dtDirector": "//span[contains(text(), '导演')]/following-sibling::a/text()",
    "dtDirectorR": "",
    "dtActor": "//span[contains(text(), '主演')]/following-sibling::a/text()",
    "dtActorR": "",
    "dtDesc": "//span[contains(text(), '简介')]/parent::text()",
    "dtDescR": "",
    "dtFromNode": "//ul[contains(@class,'nav nav-tabs')]/li/a",
    "dtFromName": "/text()",
    "dtFromNameR": "",
    "dtUrlNode": "//ul[contains(@class,'myui-content__list')]",
    "dtUrlSubNode": "/li/a",
    "dtUrlId": "@href",
    "dtUrlIdR": "/play/(\\S+).html",
    "dtUrlName": "/text()",
    "dtUrlNameR": "",
    "playUrl": "https://www.ml1080.com/play/{playUrl}.html",
    "playUa": "",
    "searchUrl": "https://www.ml1080.com/search.html?wd={wd}&submit=",
    "scVodNode": "//ul[@class='myui-vodlist__media clearfix']/li//a[contains(@class,'myui-vodlist__thumb')]",
    "scVodName": "/@title",
    "scVodId": "/@href",
    "scVodIdR": "/move/(\\w+).html",
    "scVodImg": "/@data-original",
    "scVodMark": "/span[@class='pic-text text-right']/text()"
}
