{
    "author": "春风",
    "ua": "",
    "homeUrl": "https://www.qkw2.com/",
    "dcVipFlag": "true",
    "pCfgJs": "https://www.qkw2.com/static/js/playerconfig.js",
    "pCfgJsR": "MacPlayerConfig.player_list=([\\w\\W]*?),MacPlayerConfig.downer_list=",
    "dcShow2Vip": {},
    "dcPlayUrl": "true",
    "cateManual": {
        "电影": "1",
        "连续剧": "2",
        "动漫": "4",
        "综艺": "3"
    },
    "homeVodNode": "//ul[@class='vodlist vodlist_wi clearfix']/li",
    "homeVodName": "/a/@title",
    "homeVodId": "/a/@href",
    "homeVodIdR": "/vod/detail/(\\w+).html",
    "homeVodImg": "/a/@data-original",
    "homeVodImgR": "",
    "homeVodMark": "/span[@class='pic-text text-right']/text()",
    "cateUrl": "http://1090ys2.com/whole/{cateId}/page/{catePg}.html",
    "cateVodNode": "",
    "cateVodName": "/@title",
    "cateVodId": "/@href",
    "cateVodIdR": "/show/(\\w+).html",
    "cateVodImg": "/@data-original",
    "cateVodImgR": "",
    "cateVodMark": "/span[@class='pic-text text-right']/text()",
    "dtUrl": "https://www.qkw2.com/vod/play/{vid}-1-1.html",
    "dtNode": "//body",
    "dtName": "//h3[@class='title']/text()",
    "dtNameR": "",
    "dtImg": "//div[@class='play_vlist cblock']/div[contains(@class,'play_vlist_thumb')]/@data-original",
    "dtImgR": "",
    "dtCate": "//span[contains(text(), '类型')]/following-sibling::a/text()",
    "dtCateR": "",
    "dtYear": "//span[contains(text(), '年份')]/following-sibling::a/text()",
    "dtYearR": "",
    "dtArea": "//span[contains(text(), '地区')]/following-sibling::a/text()",
    "dtAreaR": "",
    "dtDirector": "//span[contains(text(), '导演')]/following-sibling::a/text()",
    "dtDirectorR": "",
    "dtActor": "//span[contains(text(), '主演')]/parent::text()",
    "dtActorR": "",
    "dtDesc": "//div[@class='panel play_content']/text()",
    "dtDescR": "",
    "dtFromNode": "//ul[@class='title_nav']/li/label/span",
    "dtFromName": "/text()",
    "dtFromNameR": "",
    "dtUrlNode": "//ul[@class='content_playlist clearfix']",
    "dtUrlSubNode": "/li/a",
    "dtUrlId": "@href",
    "dtUrlIdR": "/vod/play/(\\S+).html",
    "dtUrlName": "/text()",
    "dtUrlNameR": "",
    "playUrl": "http://1090ys2.com/play/{playUrl}.html",
    "playUa": "",
    "searchUrl": "{wd}",
    "scVodNode": "",
    "scVodName": "/@title",
    "scVodId": "/@href",
    "scVodIdR": "/show/(\\w+).html",
    "scVodImg": "/@data-original",
    "scVodMark": "/span[@class='pic-text text-right']/text()"
}
