{
    "author": "春风",
    "ua": "",
    "homeUrl": "https://www.upyunso.com",
    "dcVipFlag": "true",

    "dcPlayUrl": "true",
    "cateManual": {
   
    },
    "homeVodNode": "",
    "homeVodName": "",
    "homeVodId": "",
    "homeVodIdR": "",
    "homeVodImg": "",
    "homeVodImgR": "",
    "homeVodMark": "",
    "cateUrl": "",
    "cateVodNode": "",
    "cateVodName": "",
    "cateVodId": "",
    "cateVodIdR": "",
    "cateVodImg": "",
    "cateVodImgR": "",
    "cateVodMark": "",
    "dtUrl": "http://1090ys2.com/show/{vid}.html",
    "dtNode": "//body",
    "dtName": "//div[@class='stui-content__thumb']/a/@title",
    "dtNameR": "",
    "dtImg": "",
    "dtImgR": "",
    "dtCate": "//span[contains(text(), '类型')]/following-sibling::a/text()",
    "dtCateR": "",
    "dtYear": "",
    "dtYearR": "",
    "dtArea": "",
    "dtAreaR": "",
    "dtDirector": "//span[contains(text(), '导演')]/following-sibling::a/text()",
    "dtDirectorR": "",
    "dtActor": "//span[contains(text(), '主演')]/parent::text()",
    "dtActorR": "",
    "dtDesc": "",
    "dtDescR": "",
    "dtFromNode": "",
    "dtFromName": "/text()",
    "dtFromNameR": "",
    "dtUrlNode": "",
    "dtUrlSubNode": "/li/a",
    "dtUrlId": "@href",
    "dtUrlIdR": "/play/(\\S+).html",
    "dtUrlName": "/text()",
    "dtUrlNameR": "",
    "playUrl": "http://1090ys2.com/play/{playUrl}.html",
    "playUa": "",
    "searchUrl": "https://www.upyunso.com/search.html?page=1&keyword={wd}",
    "scVodNode": "//div[@id='res_list']/div[@class='resource-item border-dashed-eee'][position()>2]/div[@class='main-info']",
    "scVodName": "/h1/a/text()",
    "scVodId": "/div/p[1]/a/@href",
    "scVodIdR": "download.html?zid=(\\S+)",
    "scVodImg": "/h1/img/@src",
    "scVodMark": ""
}
