{
    "author": "春风",
    "ua": "",
    "homeUrl": "https://www.nfuxs.com/index.php",
    "dcVipFlag": "true",
    "pCfgJs": "https://www.nfuxs.com/static/js/playerconfig.js",
    "pCfgJsR": "MacPlayerConfig.player_list=([\\w\\W]*?),MacPlayerConfig.downer_list=",
    "dcShow2Vip": {},
    "dcPlayUrl": "true",
    "cateManual": {
        "电影": "1",
        "连续剧": "2",
        "动漫": "3",
        "综艺": "4"
    },
    "homeVodNode": "//div[@class='module-item']",
    "homeVodName": "//div[@class='module-item-pic']/a/@title",
    "homeVodId": "//div[@class='module-item-pic']/a/@href",
    "homeVodIdR": "/index.php/vod/detail/id/(\\w+).html",
    "homeVodImg": "//div[@class='module-item-pic']/img/@data-src",
    "homeVodImgR": "",
    "homeVodMark": "//div[@class='module-item-text']/text()",
    "cateUrl": "https://www.nfuxs.com/index.php/vod/show/id/{cateId}/page/{catePg}.html",
    "cateVodNode": "//div[@class='module-item']",
    "cateVodName": "//div[@class='module-item-pic']/a/@title",
    "cateVodId": "//div[@class='module-item-pic']/a/@href",
    "cateVodIdR": "/index.php/vod/detail/id/(\\w+).html",
    "cateVodImg": "//div[@class='module-item-pic']/img/@data-src",
    "cateVodImgR": "",
    "cateVodMark": "//div[@class='module-item-text']/text()",
    "dtUrl": "https://www.nfuxs.com/index.php/vod/detail/id/{vid}.html",
    "dtNode": "//body",
    "dtName": "//h1[@class='page-title']/text()",
    "dtNameR": "",
    "dtImg": "//div[@class='video-cover']//div[@class='module-item-pic']/img/@data-src",
    "dtImgR": "",
    "dtCate": "//span[contains(text(), '类型')]/following-sibling::a/text()",
    "dtCateR": "//div[@class='tag-link']/span/following-sibling::a/text()",
    "dtYear": "//div[@class='tag-link']/span[@class='slash']/parent::/div/following-sibling::a/text()",
    "dtYearR": "",
    "dtArea": "//div[@class='tag-link']/span[@class='slash']/parent::/div/following-sibling::a[2]/text()",
    "dtAreaR": "",
    "dtDirector": "//span[contains(text(), '导演')]/following-sibling::div/a/text()",
    "dtDirectorR": "",
    "dtActor": "//span[contains(text(), '主演')]/following-sibling::div/a/text()",
    "dtActorR": "",
    "dtDesc": "//span[contains(text(), '剧情')]/following-sibling::div/span/text()",
    "dtDescR": "",
    "dtFromNode": "//div[@class='module-tab-content']/div/span",
    "dtFromName": "/text()",
    "dtFromNameR": "",
    "dtUrlNode": "//div[@class='module-blocklist']/div",
    "dtUrlSubNode": "/a",
    "dtUrlId": "@href",
    "dtUrlIdR": "/index.php/vod/play/(\\S+).html",
    "dtUrlName": "/span/text()",
    "dtUrlNameR": "",
    "playUrl": "https://www.nfuxs.com/index.php/vod/play/{playUrl}.html",
    "playUa": "",
    "searchUrl": "{wd}",
    "scVodNode": "",
    "scVodName": "/@title",
    "scVodId": "/@href",
    "scVodIdR": "/show/(\\w+).html",
    "scVodImg": "/@data-original",
    "scVodMark": "/span[@class='pic-text text-right']/text()"
}
